### PR TITLE
Add repositories prefixes

### PR DESCRIPTION
**Pull request by JulienBreux**
@Seize/developpers & @Seize/devops Need your opinion 😸

### CODE REVIEW

**Comment by potsky** [comment]
👍

**Comment by psegalen** [comment]
👌

**Comment by skurtzemann** [comment]
For the `infra-` prefix I will perhaps add some distinctions for terraform, packer, ansible configuration.
For example
* `infra-terraform-`, `infra-tf-`, or just `terraform-`

What do you think ?

**Comment by JulienBreux** [comment]
Very good idea!

**Comment by skurtzemann** [comment]
Which one do you prefer ?

**Comment by skurtzemann** [comment]
Another thing, where do we store the documentation ?
I a dedicated `doc-` repo or in a `docs/` folder into the project repo ?

**Comment by JulienBreux** [comment]
@skurtzemann it's perfect `infra-tf-`.

Always repo with a `docs/` dir. Code documentation must be versionned with project.

And why not "join" in one internal site, for example ; https://docs.seize.io or https://d.s3e.tv :trollface:

**Comment by skurtzemann** [comment]
@JulienBreux : fine I also prefer `infra-tf-` 👍

**Comment by potsky** [comment]
> And why not "join" in one internal site, for example ; https://docs.seize.io or https://d.s3e.tv

Very good idea 👍

**Pull request merged**
